[tool.poetry]
name = "devsec"
version = "0.1.0"
description = ""
authors = ["cray75 <craysmith75@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
